[package]
name = "reward_json"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre.workspace = true
alloy.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
eigen_types.workspace = true